// 실제 상품 사진: 회사 자체 보유 파일(로컬 저장) + 공급사 카탈로그 제공 사진만 사용.
// ※ 2026-08-30: 기존에 여기 있던 blog.naver.com(blogthumb.pstatic.net) 링크 11개는
//   전부 죽은 링크(404)로 확인되어 photo:null로 전환하고 이 목록에서 제거함.
//   자세한 경위는 CLAUDE.md "원본 12개 상품 사진 깨짐" 항목 참고.
const PHOTOS = {
  // 공급사 카탈로그 제공 사진 (K2코리아 / 블랙야크 / 대신화학 / 에스큐브 / 빅스탑)
  k2_117be: "product-k2-117be.jpg",
  k2_107be: "product-k2-107be.jpg",
  k2_51n: "product-k2-51n.jpg",
  k2_26: "product-k2-26.jpg",
  blackyakYak501d: "product-blackyak-yak501d.jpg",
  daeshinBoots: "product-daeshin-boots.jpg",
  scubeInsulatedBoots: "product-scube-insulated-boots.jpg",
  vicstopChemicalBoots: "product-vicstop-chemical-boots.jpg",
  // 사용자가 보내준 안전용품 모음 사진(현장 사진 속 실제 장비)에서 품목별로 잘라낸 임시 사진.
  // 나중에 각 상품 전용 사진을 받으면 아래 값만 교체하면 됨 (2026-08-30, CLAUDE.md 참고)
  helmetWhite: "product-helmet-white.jpg",
  helmetYellow: "product-helmet-yellow.jpg",
  safetyBoots: "product-safety-boots.jpg",
  safetyVest: "product-safety-vest.jpg",
  workGloves: "product-work-gloves.jpg",
  safetyGoggles: "product-safety-goggles.jpg",
  dustMask: "product-dust-mask.jpg",
  // 2026-08-31: 사용자가 보내준 브랜드별 공급사 카탈로그 PDF(코오롱/네파/지벤/아이더세이프티/
  // 블랙야크/국제안전화/장화/보안경/귀마개, 총 10개 파일)에서 대표 모델을 골라 등록.
  // 자세한 경위는 CLAUDE.md "브랜드 카탈로그 대량 등록" 항목 참고.
  kolonKs606d: "product-kolon-ks606d.jpg",
  kolonKs601d: "product-kolon-ks601d.jpg",
  kolonKs604d: "product-kolon-ks604d.jpg",
  nepaGt36d: "product-nepa-gt36d.jpg",
  nepaGt92: "product-nepa-gt92.jpg",
  nepaGt124: "product-nepa-gt124.jpg",
  zebenZb234: "product-zeben-zb234.jpg",
  zebenZb233: "product-zeben-zb233.jpg",
  zebenZb232: "product-zeben-zb232.jpg",
  eiderEs611: "product-eider-es611.jpg",
  eiderEs612: "product-eider-es612.jpg",
  eiderEs610: "product-eider-es610.jpg",
  blackyakTrixH: "product-blackyak-trixh.jpg",
  blackyakYak509d: "product-blackyak-yak509d.jpg",
  blackyakYak409dBe: "product-blackyak-yak409d-be.jpg",
  intlTv620: "product-intl-tv620.jpg",
  intlAe622: "product-intl-ae622.jpg",
  intlAr633: "product-intl-ar633.jpg",
  scubeCp808: "product-scube-cp808.jpg",
  vicstopPs01: "product-vicstop-ps01.jpg",
  finewellSw801: "product-finewell-sw801.jpg",
  scubeHvInsulated: "product-scube-hv-insulated.jpg",
  kolonKe101: "product-kolon-ke101.jpg",
  kolonKe201: "product-kolon-ke201.jpg",
  m3Virtua: "product-3m-virtua.jpg",
  doilGoggle: "product-doil-goggle.jpg",
  m3H10a: "product-3m-h10a.jpg",
  m3_1100: "product-3m-1100.jpg",
  // 2026-09-01 추가 — 용접우산 (프로신소재, navimro.com 최저가 확인 후 등록)
  weldingUmbrella: "product-welding-umbrella.jpg",
};

// Shared product catalog — used by product listing cards and the product detail page.
const PRODUCTS = [
  // 건설안전용품
  { id: "KM-HM-001", name: "ABS 산업용 안전모 (백색)", price: 12000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KC 인증", origin: "국내", badge: "", hit: true, photo: PHOTOS.helmetWhite,
    desc: "건설 현장 필수 보호구인 ABS 소재 안전모입니다. 충격 흡수성이 뛰어나며 장시간 착용해도 무게 부담이 적습니다." },
  { id: "KM-HM-003", name: "통풍형 안전모 (황색)", price: 15000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KC 인증", origin: "국내", badge: "NEW", hit: false, photo: PHOTOS.helmetYellow,
    desc: "통풍구가 있어 여름철 현장에서도 쾌적하게 착용할 수 있는 안전모입니다." },
  { id: "KM-SB-005", name: "안전대 (2줄 걸이)", price: 45000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KS 표준", origin: "국내", badge: "", hit: false, photo: null,
    desc: "고소 작업 시 추락을 방지하는 2줄 걸이 안전대로, 이동 중에도 상시 체결 상태를 유지할 수 있습니다." },
  { id: "KM-SH-014", name: "절연 안전화 (6인치)", price: 68000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KC 인증", origin: "국내", badge: "", hit: false, photo: PHOTOS.safetyBoots,
    desc: "전기 작업 현장에 적합한 절연 기능을 갖춘 6인치 안전화입니다." },
  { id: "KM-NT-002", name: "추락방지망 (그물망)", price: 120000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KS 표준", origin: "국내", badge: "", hit: false, photo: null,
    desc: "고소 작업 구간에 설치하는 추락방지망으로, 낙하물 및 추락 사고를 예방합니다." },
  { id: "KM-SG-009", name: "안전표지판 세트", price: 35000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KC 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "현장 위험 요소를 안내하는 표준 규격 안전표지판 세트입니다." },
  { id: "KM-SR-011", name: "비계용 안전난간대", price: 55000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "KS 표준", origin: "국내", badge: "", hit: false, photo: null,
    desc: "비계 설치 구간의 추락 사고를 예방하는 조립식 안전난간대입니다." },
  { id: "KM-CB-003", name: "안전벨트 고리 (카라비너)", price: 18000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "CE 인증", origin: "수입", badge: "", hit: false, photo: null,
    desc: "안전대와 함께 사용하는 고강도 카라비너 고리로, 국제 인증을 획득한 제품입니다." },
  { id: "KM-SH-020", name: "K2 워킹화 (K2-117BE, 베이지)", price: 58000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "벨크로 스트랩형", origin: "국내", badge: "", hit: false, photo: PHOTOS.k2_117be,
    desc: "K2 세이프티의 벨크로 스트랩형 워킹화입니다. 착탈이 편리해 현장 출입이 잦은 작업에 적합합니다.",
    details: [
      { title: "데저트 샌드 컬러", desc: "사무직 환경에도 잘 어울리는 밝은 톤의 컬러를 적용해, 흙·먼지 등에 의한 오염이 눈에 덜 띕니다." },
      { title: "타이크로스밴드", desc: "새롭게 개발한 신소재 스트랩을 적용해 경량성·통기성·투습성·발수 성능을 확보했습니다." },
    ],
    detailImage: "product-k2-117be-details.jpg" },
  { id: "KM-SH-021", name: "K2 스틸토캡 안전화 (K2-107BE)", price: 89000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·BOA 다이얼", origin: "국내", badge: "", hit: false, photo: PHOTOS.k2_107be,
    desc: "스틸토캡으로 발끝을 보호하고, BOA 다이얼로 발등 조임을 세밀하게 조절할 수 있는 K2 안전화입니다.",
    details: [
      { title: "스틸토캡", desc: "발끝 부위에 강철 소재를 넣어 낙하물·충격으로부터 발가락을 보호합니다." },
      { title: "BOA 다이얼", desc: "신발끈 없이 다이얼을 돌리는 방식으로 발등 조임을 세밀하게 조절할 수 있습니다." },
    ] },
  { id: "KM-SH-022", name: "K2 방한 안전화 (K2-51N)", price: 98000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "GORE-TEX 방한", origin: "국내", badge: "", hit: false, photo: PHOTOS.k2_51n,
    desc: "GORE-TEX 소재를 적용한 K2 방한 안전화로, 동절기 외부 현장 작업에 적합합니다.",
    details: [
      { title: "GORE-TEX 소재", desc: "방수·투습 기능을 갖춘 고어텍스 소재를 적용해 눈·비가 있는 현장에서도 발이 젖지 않습니다." },
      { title: "방한 기능", desc: "겨울철 저온 환경에서도 보온성을 유지해 동절기 외부 현장 작업에 적합합니다." },
    ] },
  { id: "KM-SH-023", name: "K2 비계화 (K2-26)", price: 79000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "비계작업용", origin: "국내", badge: "", hit: false, photo: PHOTOS.k2_26,
    desc: "비계 설치·해체 작업에 특화된 K2 비계화로, 발목 지지력과 접지력을 강화했습니다.",
    details: [
      { title: "발목 지지력 강화", desc: "비계 설치·해체 작업 중에도 발목을 안정적으로 잡아줍니다." },
      { title: "접지력 강화", desc: "미끄러운 비계 구조물 위에서도 안정적인 접지력을 제공합니다." },
    ] },
  { id: "KM-SH-024", name: "블랙야크 안전화 (YAK-501D)", price: 85000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "BOA 다이얼", origin: "국내", badge: "", hit: false, photo: PHOTOS.blackyakYak501d,
    desc: "블랙야크의 BOA 다이얼 적용 안전화로, 끈 없이 다이얼로 조임을 조절할 수 있습니다.",
    details: [
      { title: "BOA 다이얼", desc: "신발끈 없이 다이얼을 돌리는 방식으로 조임을 간편하게 조절할 수 있습니다." },
      { title: "블랙야크 브랜드", desc: "아웃도어 전문 브랜드 블랙야크의 노하우가 담긴 안전화 라인입니다." },
    ] },
  { id: "KM-SH-025", name: "대신 안전 장화", price: 32000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "PVC 인젝션", origin: "국내", badge: "", hit: false, photo: PHOTOS.daeshinBoots,
    desc: "우천·습지 현장에 적합한 PVC 인젝션 공법의 대신 안전 장화입니다.",
    details: [
      { title: "PVC 인젝션 공법", desc: "이음새 없는 일체형 사출 성형으로 제작되어 내구성과 방수성이 뛰어납니다." },
      { title: "우천·습지 작업에 적합", desc: "물이 많은 현장에서도 편하게 착용할 수 있습니다." },
    ] },
  { id: "KM-SH-026", name: "에스큐브 절연장화 (고압용)", price: 62000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "내전압 절연", origin: "국내", badge: "", hit: false, photo: PHOTOS.scubeInsulatedBoots,
    desc: "전기 작업 현장에서 사용하는 에스큐브 고압용 절연장화입니다.",
    details: [
      { title: "내전압 절연 구조", desc: "고압 전기 작업 현장에서 감전 위험을 낮춰주는 절연 구조로 제작되었습니다." },
      { title: "고압용 규격", desc: "고압 전기 작업 환경에 맞춘 규격의 절연장화입니다." },
    ] },
  { id: "KM-SH-027", name: "빅스탑 내화학 장화", price: 48000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "내화학 소재", origin: "국내", badge: "", hit: false, photo: PHOTOS.vicstopChemicalBoots,
    desc: "화학 약품 취급 현장에 적합한 빅스탑 내화학 장화입니다.",
    details: [
      { title: "내화학 소재", desc: "화학 약품에 강한 소재로 제작되어 약품을 다루는 현장에 적합합니다." },
      { title: "빅스탑 브랜드", desc: "산업용 보호장화 전문 제조사 빅스탑의 제품입니다." },
    ] },

  // 2026-08-31 추가 — 브랜드 카탈로그 대량 등록분 (코오롱/네파/지벤/아이더세이프티/블랙야크/국제안전화/장화)
  { id: "KM-SH-028", name: "코오롱 안전화 (KS-606D)", price: 92000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.kolonKs606d,
    desc: "코오롱글로벌의 다이얼 조임 방식 안전화로, 발볼이 편안한 와이드 핏 설계가 적용되었습니다.",
    detailImage: "product-kolon-ks606d-details.jpg" },
  { id: "KM-SH-029", name: "코오롱 안전화 (KS-601D)", price: 88000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.kolonKs601d,
    desc: "코오롱글로벌의 다이얼 조임 방식 미드컷 안전화입니다.",
    detailImage: "product-kolon-ks601d-details.jpg" },
  { id: "KM-SH-030", name: "코오롱 안전화 (KS-604D)", price: 95000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·반사 스트립", origin: "국내", badge: "", hit: false, photo: PHOTOS.kolonKs604d,
    desc: "야간 시인성을 높이는 반사 스트립이 적용된 코오롱글로벌 다이얼 조임 안전화입니다.",
    detailImage: "product-kolon-ks604d-details.jpg" },
  { id: "KM-SH-031", name: "네파 안전화 (GT-36D, 다이얼)", price: 79000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.nepaGt36d,
    desc: "네파의 다이얼 조임 방식 트레킹화 스타일 안전화입니다.",
    detailImage: "product-nepa-gt36d-details.jpg" },
  { id: "KM-SH-032", name: "네파 안전화 (GT-92)", price: 69000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·슬립온", origin: "국내", badge: "", hit: false, photo: PHOTOS.nepaGt92,
    desc: "끈 없이 신고 벗기 편한 슬립온 형태에 다이얼 조임을 더한 네파 안전화입니다.",
    detailImage: "product-nepa-gt92-details.jpg" },
  { id: "KM-SH-033", name: "네파 안전화 (GT-124)", price: 75000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.nepaGt124,
    desc: "가벼운 착화감의 러닝화 스타일에 다이얼 조임을 적용한 네파 안전화입니다.",
    detailImage: "product-nepa-gt124-details.jpg" },
  { id: "KM-SH-034", name: "지벤 안전화 (ZB-234)", price: 72000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·방수", origin: "국내", badge: "", hit: false, photo: PHOTOS.zebenZb234,
    desc: "방수 기능을 갖춘 지벤의 다이얼 조임 안전화입니다.",
    detailImage: "product-zeben-zb234-details.jpg" },
  { id: "KM-SH-035", name: "지벤 안전화 (ZB-233)", price: 68000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·방수", origin: "국내", badge: "", hit: false, photo: PHOTOS.zebenZb233,
    desc: "방수 기능을 갖춘 지벤의 다이얼 조임 안전화입니다.",
    detailImage: "product-zeben-zb233-details.jpg" },
  { id: "KM-SH-036", name: "지벤 안전화 (ZB-232)", price: 74000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·반사 스트립", origin: "국내", badge: "", hit: false, photo: PHOTOS.zebenZb232,
    desc: "야간 시인성을 높이는 반사 스트립이 적용된 지벤 다이얼 조임 안전화입니다.",
    detailImage: "product-zeben-zb232-details.jpg" },
  { id: "KM-SH-037", name: "아이더세이프티 절연화 (ES611)", price: 82000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·절연", origin: "국내", badge: "", hit: false, photo: PHOTOS.eiderEs611,
    desc: "전기 작업 현장에 적합한 절연 기능을 갖춘 아이더세이프티 다이얼 조임 안전화입니다.",
    detailImage: "product-eider-es611-details.jpg" },
  { id: "KM-SH-038", name: "아이더세이프티 절연화 (ES612)", price: 82000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·절연", origin: "국내", badge: "", hit: false, photo: PHOTOS.eiderEs612,
    desc: "전기 작업 현장에 적합한 절연 기능을 갖춘 아이더세이프티 다이얼 조임 안전화입니다.",
    detailImage: "product-eider-es612-details.jpg" },
  { id: "KM-SH-039", name: "아이더세이프티 안전화 (ES610)", price: 71000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.eiderEs610,
    desc: "가벼운 착화감의 아이더세이프티 다이얼 조임 안전화입니다.",
    detailImage: "product-eider-es610-details.jpg" },
  { id: "KM-SH-040", name: "블랙야크 활동화 (트릭스H, 베이지)", price: 78000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "BOA 다이얼·듀얼 컴포트 인솔", origin: "국내", badge: "", hit: false, photo: PHOTOS.blackyakTrixH,
    desc: "충격 흡수 인솔과 방탄성유 내타편이 적용된 블랙야크 BOA 다이얼 활동화입니다.",
    detailImage: "product-blackyak-trixh-details.jpg" },
  { id: "KM-SH-041", name: "블랙야크 안전화 (YAK-509D, 블랙)", price: 81500, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "BOA 다이얼·GORE-TEX", origin: "국내", badge: "", hit: false, photo: PHOTOS.blackyakYak509d,
    desc: "GORE-TEX 방수 소재를 적용한 블랙야크 BOA 다이얼 안전화입니다.",
    detailImage: "product-blackyak-yak509d-details.jpg" },
  { id: "KM-SH-042", name: "블랙야크 안전화 (YAK-409D, 베이지)", price: 74500, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "BOA 다이얼·GORE-TEX", origin: "국내", badge: "", hit: false, photo: PHOTOS.blackyakYak409dBe,
    desc: "GORE-TEX 방수 소재를 적용한 블랙야크 BOA 다이얼 안전화입니다.",
    detailImage: "product-blackyak-yak409d-be-details.jpg" },
  { id: "KM-SH-043", name: "국제안전화 (TV-620)", price: 65000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·끈 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.intlTv620,
    desc: "트레킹화 스타일의 끈 조임 방식 국제안전화입니다.",
    detailImage: "product-intl-tv620-details.jpg" },
  { id: "KM-SH-044", name: "국제안전화 절연화 (AE-622)", price: 79000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임·절연", origin: "국내", badge: "", hit: false, photo: PHOTOS.intlAe622,
    desc: "전기 작업 현장에 적합한 절연 기능을 갖춘 국제안전화 다이얼 조임 모델입니다.",
    detailImage: "product-intl-ae622-details.jpg" },
  { id: "KM-SH-045", name: "국제안전화 (AR-633)", price: 68000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "스틸토캡·다이얼 조임", origin: "국내", badge: "", hit: false, photo: PHOTOS.intlAr633,
    desc: "다이얼 조임 방식의 국제안전화 안전화입니다.",
    detailImage: "product-intl-ar633-details.jpg" },
  { id: "KM-SH-046", name: "에스큐브 안전 요딩장화 (CP-808)", price: 19000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "PVC 인젝션", origin: "국내", badge: "", hit: false, photo: PHOTOS.scubeCp808,
    desc: "우천·습지 현장에 적합한 PVC 인젝션 공법의 에스큐브 요딩(무릎밑) 장화입니다.",
    detailImage: "product-scube-cp808-details.jpg" },
  { id: "KM-SH-047", name: "빅스탑 안전 요딩장화 (PS-01)", price: 24700, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "PVC 인젝션", origin: "국내", badge: "", hit: false, photo: PHOTOS.vicstopPs01,
    desc: "우천·습지 현장에 적합한 빅스탑 요딩(무릎밑) 안전장화입니다.",
    detailImage: "product-vicstop-ps01-details.jpg" },
  { id: "KM-SH-048", name: "파인웰 안전 요딩장화 (SW-801)", price: 19000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "PVC 인젝션·미끄럼방지", origin: "국내", badge: "", hit: false, photo: PHOTOS.finewellSw801,
    desc: "미끄럼방지 밑창을 적용한 파인웰 요딩(무릎밑) 안전장화입니다.",
    detailImage: "product-finewell-sw801-details.jpg" },
  { id: "KM-SH-049", name: "에스큐브 절연장화 (특고압용)", price: 68000, cat: "construction", catLabel: "건설안전용품", catPage: "products-construction.html", spec: "내전압 절연·특고압", origin: "국내", badge: "", hit: false, photo: PHOTOS.scubeHvInsulated,
    desc: "특고압 전기 작업 현장에서 사용하는 에스큐브 절연장화입니다.",
    detailImage: "product-scube-hv-insulated-details.jpg" },

  // 개인안전용품
  { id: "KM-MK-022", name: "방진마스크 2급 (10매입)", price: 9900, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KF80", origin: "국내", badge: "", hit: false, photo: PHOTOS.dustMask,
    desc: "분진이 많은 작업 환경에서 호흡기를 보호하는 2급 방진마스크 10매입 제품입니다." },
  { id: "KM-GG-007", name: "산업용 보안경 (김서림방지)", price: 7500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KC 인증", origin: "국내", badge: "", hit: false, photo: PHOTOS.safetyGoggles,
    desc: "김서림 방지 코팅이 적용되어 장시간 착용해도 시야가 흐려지지 않는 보안경입니다." },
  { id: "KM-GL-015", name: "내화학 안전장갑", price: 6800, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "CE 인증", origin: "수입", badge: "", hit: false, photo: null,
    desc: "화학 약품 취급 작업에 적합한 내화학성 소재의 안전장갑입니다." },
  { id: "KM-CW-004", name: "방한 작업복", price: 42000, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KC 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "동절기 실외 현장 작업에 적합한 보온성 높은 방한 작업복입니다." },
  { id: "KM-EP-008", name: "귀마개 (소음차단)", price: 3500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KC 인증", origin: "수입", badge: "NEW", hit: false, photo: PHOTOS.m3_1100,
    desc: "소음이 심한 작업 환경에서 청력을 보호하는 무줄 폼타입 귀마개입니다.",
    detailImage: "product-3m-1100-details.jpg" },
  { id: "KM-VT-006", name: "안전조끼 (형광)", price: 8900, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KS 표준", origin: "국내", badge: "", hit: false, photo: PHOTOS.safetyVest,
    desc: "야간 및 저조도 현장에서 작업자의 시인성을 높여주는 형광 안전조끼입니다." },
  { id: "KM-GG-012", name: "방진고글", price: 9500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KC 인증", origin: "수입", badge: "", hit: false, photo: PHOTOS.doilGoggle,
    desc: "분진과 비산물로부터 눈을 보호하는 밀착형 방진고글입니다.",
    detailImage: "product-doil-goggle-details.jpg" },
  { id: "KM-GL-019", name: "미끄럼방지 작업장갑", price: 4200, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "KS 표준", origin: "국내", badge: "", hit: true, photo: PHOTOS.workGloves,
    desc: "손바닥 코팅 처리로 그립력을 높인 미끄럼방지 작업장갑입니다." },

  // 2026-08-31 추가 — 보안경/귀마개 브랜드 카탈로그 등록분
  { id: "KM-GG-016", name: "코오롱 투명보안경 (KE-101)", price: 6500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "PC 렌즈", origin: "국내", badge: "", hit: false, photo: PHOTOS.kolonKe101,
    desc: "가벼운 착용감의 코오롱글로벌 투명 보안경입니다.",
    detailImage: "product-kolon-ke101-details.jpg" },
  { id: "KM-GG-017", name: "코오롱 차광보안경 (KE-201)", price: 8500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "PC 렌즈·차광", origin: "국내", badge: "", hit: false, photo: PHOTOS.kolonKe201,
    desc: "야외 작업 시 눈부심을 줄여주는 코오롱글로벌 차광 보안경입니다.",
    detailImage: "product-kolon-ke201-details.jpg" },
  { id: "KM-GG-018", name: "3M 보안경 (VIRTUA)", price: 9500, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "PC 렌즈", origin: "수입", badge: "", hit: false, photo: PHOTOS.m3Virtua,
    desc: "가벼운 착용감의 3M 투명 보안경입니다.",
    detailImage: "product-3m-virtua-details.jpg" },
  { id: "KM-EP-013", name: "3M 청력보호구 (헤드밴드형)", price: 28000, cat: "personal", catLabel: "개인안전용품", catPage: "products-personal.html", spec: "헤드밴드형", origin: "수입", badge: "", hit: false, photo: PHOTOS.m3H10a,
    desc: "장시간 착용에도 편안한 3M 헤드밴드형 청력보호구(이어머프)입니다.",
    detailImage: "product-3m-h10a-details.jpg" },

  // 소방안전용품
  { id: "KM-FE-001", name: "분말 소화기 (3.3kg)", price: 25000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "초기 화재 진압에 적합한 3.3kg 분말 소화기입니다." },
  { id: "KM-FD-002", name: "화재감지기 (연기식)", price: 32000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "연기를 감지해 화재 초기 경보를 울리는 연기식 화재감지기입니다." },
  { id: "KM-FB-003", name: "소화전함 (옥내)", price: 180000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "옥내소화전 설비에 사용되는 표준 규격 소화전함입니다." },
  { id: "KM-EL-005", name: "비상유도등", price: 28000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "NEW", hit: false, photo: null,
    desc: "정전 시에도 대피 방향을 안내하는 비상유도등입니다." },
  { id: "KM-FS-007", name: "방화복 세트", price: 350000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "화재 현장 대응을 위한 내열·내화 소재의 방화복 세트입니다." },
  { id: "KM-ES-004", name: "완강기 (피난기구)", price: 220000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: false, photo: null,
    desc: "고층 건물 비상 대피 시 사용하는 완강기(피난기구)입니다." },
  { id: "KM-FH-006", name: "소화기 거치대", price: 9000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KS 표준", origin: "국내", badge: "", hit: false, photo: null,
    desc: "소화기를 안전하게 비치할 수 있는 벽걸이형 거치대입니다." },
  { id: "KM-EL-009", name: "비상조명등", price: 24000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "KFI 인증", origin: "국내", badge: "", hit: true, photo: null,
    desc: "정전 시 대피로를 밝혀주는 비상조명등입니다." },

  // 2026-09-01 추가 — 용접우산(사각/원형). 매입처: 프로신소재(navimro.com B2B), 동일 사이즈 기준
  // 타사 최저가 재확인 완료 (애니원 28,990원, 웰드플러스 26,990원 등보다 저렴함을 확인).
  { id: "KM-WU-010", name: "용접우산 (사각형 700×700mm)", price: 35700, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "사각 700×700mm · 버미글라스", origin: "국내", badge: "NEW", hit: false, photo: PHOTOS.weldingUmbrella,
    desc: "고소 용접 작업 시 발생하는 불티와 슬래그의 비산을 막아주는 사각형 용접우산입니다. 내열성이 뛰어난 버미글라스(유리섬유) 소재로 제작되어 화재 예방과 작업자 보호에 효과적입니다. 배관이나 철 구조물 등 상부에서 진행되는 일반적인 용접 작업에 주로 사용됩니다.",
    details: [
      { title: "내열 소재", desc: "약 1,200℃(순간)·약 800℃(지속) 온도에 견디는 버미글라스(석면 대체 소재) 원단으로 제작되었습니다." },
      { title: "취급 시 유의사항", desc: "유리섬유 소재 특성상 손에 묻을 수 있어 취급 전 장갑 착용을 권장합니다." },
    ],
    detailImage: "product-welding-umbrella-details.jpg" },
  { id: "KM-WU-011", name: "용접우산 (원형 Ø800mm)", price: 33000, cat: "fire", catLabel: "소방안전용품", catPage: "products-fire.html", spec: "원형 Ø800mm · 버미글라스", origin: "국내", badge: "NEW", hit: false, photo: PHOTOS.weldingUmbrella,
    desc: "상부 모서리나 구석진 곳의 용접 작업 시 현장을 보호하기에 적합한 원형 용접우산입니다. 내열성이 뛰어난 버미글라스(유리섬유) 소재로 제작되어 화재 예방과 작업자 보호에 효과적입니다.",
    details: [
      { title: "내열 소재", desc: "약 1,200℃(순간)·약 800℃(지속) 온도에 견디는 버미글라스(석면 대체 소재) 원단으로 제작되었습니다." },
      { title: "취급 시 유의사항", desc: "유리섬유 소재 특성상 손에 묻을 수 있어 취급 전 장갑 착용을 권장합니다." },
    ],
    detailImage: "product-welding-umbrella-details.jpg" },
];

const CAT_ICONS = {
  construction: '<path d="M4 15a8 8 0 0 1 16 0v1H4v-1Z"/><path d="M2 16h20"/><path d="M12 7V4"/>',
  personal: '<path d="M4 10c0-2 2-3 8-3s8 1 8 3v3c0 3-3 6-8 6s-8-3-8-6v-3Z"/><path d="M8 13h.01M16 13h.01"/>',
  fire: '<path d="M9 6h6l1 3H8l1-3Z"/><path d="M11 3v3M13 3v3"/><path d="M8 9h8v10a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V9Z"/><path d="M16 11l4-2"/>',
};

function formatWonPlain(amount) {
  return amount.toLocaleString('ko-KR') + '원';
}
